#!/usr/bin/env bash
# VikingExtractor, to recover images from Viking Lander operations.
# Copyright (C) 2010-2013 Cartesian Theatre <info@cartesiantheatre.com>.
#
# Public discussion on IRC available at #avaneya (irc.freenode.net) or
# on the mailing list <avaneya@lists.avaneya.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#
#
#    Maintainer Notes
#    ================
#
#    This script is automatically run when the volume is mounted, if enabled, as
#    per XDG's Desktop Application Autostart Specification. It needs to be 
#    called autorun and not autorun.sh because the latter sometimes results in 
#    the shell ignoring the shebang line and executing with POSIX enforcing sh
#    which won't work with a script depending on Bash extensions. 
#
#    The purpose of this script is to try to bootstrap the actual target 
#    application by ensuring the user has a sane execution environment with all
#    of the necessary hard dependencies (packages) pre-installed. What they 
#    don't have, they need to be informed of in a way that is meaningful on 
#    their specific distro to make their life simple (e.g. Ubuntu Software 
#    Centre). These are the runtimes that are needed:
#
#        Hard Dependencies
#        =================
#
#        * Zenity (zenity)
#
#        * Python 3 (python3)
#
#        * Python GObject bindings (python-gi >= 3.0), which should pull the 
#          distro's Gtk3+ runtimes on Ubuntu Precise and GDBus bindings...
#
#        Soft Dependencies
#        =================
#
#        * GStreamer 1.0 base plugins as a soft dependency since at time of 
#          authoring gir1.2-gst-plugins-base-1.0 and gstreamer1.0-plugins-base
#          did not ship pre-installed on Ubuntu, up to and including Precise 
#          (12.04)
#

# Useful constants...

    # Disc name and version...
    Title="Avaneya: Viking Lander Remastered DVD"
    
    # Preserve command line arguments because $@ is clobbered after calling any
    #  functions...
    Arguments=( "$@" )

    # Icon to use in windows...
    Icon=Launcher/Data/Icon.png

    # Distro name and codename...
    Distro=""
    DistroCodeName=""
    DistroPackageManager=""

    # VT100 terminal constants...
    VT100Reset=$'\033[0m'
    VT100Bold=$'\033[1m'
    VT100ColourRed=$'\033[31m'
    VT100ColourGreen=$'\033[32m'
    VT100ColourBlue=$'\033[34m'
    
    # Status symbol constants...
    SymbolStatusOk="${VT100Bold}${VT100ColourGreen}✓${VT100Reset}"
    SymbolStatusFail="${VT100Bold}${VT100ColourRed}✗${VT100Reset}"

    # The lock file containing the process ID. I had to ignore FHS 5.9.1
    #  because unfortunately some distros have non-user writable /var/lock, or
    #  at least require user to be member of some special group, such as "lock"
    #  or what have you. For now we can write the lock to home directory...
    #ProcessIDFile="/var/lock/vlr-lock"
    ProcessIDFile="$HOME/.vlr-lock"

    # Complete path to the directory containing this script...
    #AutostartScriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    AutostartScriptDirectory="$(dirname -- "$(readlink -f -- "$0")")"

    # Complete path to launcher entry point......
    PythonLauncherMain=""
    
    # True if we were the only instance of this script and managed to set a 
    #  lock...
    OwnLock=false
    
    # Set to true if EXIT trap should attempt to eject removable media...
    EjectRequested=false

    # Zenity process ID...
    ZenityProcessID=0

# Array of packages the user is missing that we need...
declare -a PackagesMissing

# Find the complete path to the script containing the launcher's entry point...
FindLauncherMain()
{
    # Alert user...
    echo -n "Looking for launcher... "

    # Check for Launcher/Source/Main.py first... (e.g. on disc)
    if [ -f "$AutostartScriptDirectory/Launcher/Source/Main.py" ] ; then
        PythonLauncherMain="$AutostartScriptDirectory/Launcher/Source/Main.py"
        echo $PythonLauncherMain $SymbolStatusOk

    # Nope. Check in local source directory... (e.g. local)
    elif [ -f "$AutostartScriptDirectory/../../Launcher/Source/Main.py" ] ; then
        PythonLauncherMain="$AutostartScriptDirectory/../../Launcher/Source/Main.py"
        echo $PythonLauncherMain $SymbolStatusOk

    # Couldn't find it anywhere...
    else
	    echo $SymbolStatusFail
        zenity --error \
            --title="Error" \
            --window-icon=$Icon \
            --text="Unable to find the Viking Lander Remastered application."
	    exit 1
    fi
}

# Set the VikingExtractor's locale directory environment variable to point to 
#  the DVD if found...
SetVikingExtractorLocaleDirectory()
{
    # Alert user...
    echo -n "Checking for local VikingExtractor l10n catalogue... "

    # Check within local media...
    if [ -f "$AutostartScriptDirectory/Extractor/locale/en_CA/LC_MESSAGES/viking-extractor.mo" ] ; then
        VE_LOCALE_DIR="$AutostartScriptDirectory/Extractor/locale"
        echo "$VE_LOCALE_DIR " $SymbolStatusOk

    # Guess systems...
    else
	    echo $SymbolStatusFail
    fi
}

# Signal trap to always run on exit... (e.g. ctrl-c)
OnExit()
{
    # Remove process ID file so no stale lock remains if we were the ones that
    #  locked it...
    if $OwnLock ; then
        rm -f "$ProcessIDFile"
    fi

    # Kill any instance of Zenity that might be still executing...
    KillZenity
    
    # If anything requested we eject the removable media on exit, do so now...
    if $EjectRequested ; then
        EjectRemovableMedia
    fi
}

# Kill Zenity...
KillZenity()
{
    # Kill any Zenity GUI if still open...
    if [ $ZenityProcessID != 0 ]; then
        
        # Send the terminate signal...
        kill $ZenityProcessID 2> /dev/null
        
        # Wait gracefully for it to exit...
        wait $ZenityProcessID 2> /dev/null
    fi
    ZenityProcessID=0
}

# Identify distro name and release code... $Distro and $DistroCodeName
IdentifyDistro()
{
    # Alert user...
    echo -n "Identifying distribution... "

	# Get the operating system family name...
	local OS=`uname`
	
	# Not running GNU...
	if [ "${OS}" != "Linux" ] ; then
	    echo $SymbolStatusFail
		echo "This autostart script is only supported on GNU/Linux..."
		exit 1
	fi

    # If lsb_release is present, this is easy to get distro and code name...
    if [ -x "`which lsb_release`" ]; then
        Distro=`lsb_release --id --short`
        DistroCodeName=`lsb_release --short --codename`

    # Otherwise fallback to tedious method of checking for distro specific 
    #  signatures in /etc...
	else

	    echo $SymbolStatusFail
		echo -n "Falling back to checking for distro specific signature in /etc... "

        # Arch...
	    if [ -f /etc/arch-release ] ; then
		    Distro='Arch'
		    DistroCodeName=""

        # Debian...
	    elif [ -f /etc/debian_version ] ; then
		    Distro=`cat /etc/lsb-release | grep '^DISTRIB_ID' | awk -F=  '{ print $2 }'`
		    DistroCodeName=`cat /etc/lsb-release | grep '^DISTRIB_CODENAME' | awk -F=  '{ print $2 }'`

	    # Mandrake...
	    elif [ -f /etc/mandrake-release ] ; then
		    Distro='Mandrake'
		    DistroCodeName=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
    
        # RedHat... (e.g. Fedora)
	    elif [ -f /etc/redhat-release ] ; then
		    Distro=`cat /etc/redhat-release |sed s/\ release.*//`
		    DistroCodeName=`cat /etc/redhat-release | sed s/.*\(// | sed s/\)//`
	
	    # SuSe...
	    elif [ -f /etc/SuSE-release ] ; then
		    Distro='SuSe'
		    DistroCodeName=`cat /etc/SuSE-release | tr "\n" ' '| sed s/VERSION.*//`

        # Unknown...
		else
		    echo $SymbolStatusFail
            zenity --error \
                --title="Error" \
                --window-icon=$Icon \
                --text="You need to install lsb_release before you can use this software. Use your distribution's package manager."
		    exit 1
	    fi
    fi

    # Determine which package manager system to use...

        # Apt based...
        if [ -x "`which apt-get 2>/dev/null`" ]; then
            DistroPackageManager="apt"

        # Pacman based...
        elif [ -x "`which pacman 2>/dev/null`" ]; then
            DistroPackageManager="pacman"

        # Yum based...
        elif [ -x "`which yum 2>/dev/null`" ]; then
            DistroPackageManager="yum"
        
        # Unknown...
        else
            echo ""
            zenity --error \
                --title="Avaneya: Viking Lander Remastered" \
                --window-icon=$Icon \
                --text="I'm sorry, but your package manager is not supported."
            exit 1
        fi

    # Lock distro identifiers...
 	readonly Distro
 	readonly DistroCodeName
 	readonly DistroPackageManager

    # Alert user of what we found...
    echo "${Distro} ${DistroCodeName} $SymbolStatusOk"
    echo "Native package manager is ${DistroPackageManager}..."
}

# Lock the script to ensure no other instances are running, otherwise silently
#  exit...
LockScript()
{
    # Alert user...
    echo -n "Checking for unique instance... "

    # Try to write lock, or fail if already exists. The noclobber option ensures
    #  the redirect will fail if the file the stream is being redirected to 
    #  already exists. This is safe because it is atomic. If successful, write
    #  our process ID out into our newly created lock...
    if ( set -o noclobber; echo "$$" > "$ProcessIDFile") 2> /dev/null; then
	    echo $SymbolStatusOk
	    OwnLock=true

    # Lock already exists. Check if still alive...
    elif [ -f $ProcessIDFile ] ; then
        
        # Get the existing process ID...
        OtherProcessID="$(cat "${ProcessIDFile}")"

        # Cat couldn't read the process ID file so other process may be just
        #  about to remove it...
        if [ $? != 0 ]; then
    	    echo $SymbolStatusFail
            exit 1
        fi        

        # Check if the other process is still alive by seeing if it could
        #  receive signals without actually sending any...
        if ! kill -0 $OtherProcessID &>/dev/null; then

            # Process is gone so assume lock is stale...
            rm -rf "${ProcessIDFile}"
    	    echo $SymbolStatusFail
            echo "Removed stale lock..."

            # Try setting the lock again...
            LockScript

        # The lock is valid because the other process is active...
        else
    	    echo $SymbolStatusFail
    	    echo "Process" $OtherProcessID "is existing instance..."
            exit 1
        fi

    # Could neither find an existing lock, nor write a new one. Some RedHat 
    #  systems and derivatives seem to need to run as a user in 'lock' group...
    else
	    echo $SymbolStatusFail
        echo "Warning: Cannot read / write $ProcessIDFile, loading anyways..."
    fi
}

# Convert sole argument to all lowercase...
LowerCase()
{
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

# Print banner...
PrintBanner()
{
    echo ""
    echo -e "  Copyright (C) 2010-2013 Cartesian Theatre. This is free"
    echo -e "  software; see Copying for copying conditions. There is NO"
    echo -e "  warranty; not even for MERCHANTABILITY or FITNESS FOR A"
    echo -e "  PARTICULAR PURPOSE.\n"
}

# Prepare the runtime environment as specific to user's distro...
InitializeRuntime()
{
    # Array for a list of packages that's always needed...
    declare -a local PackagesRequired;

    # Calculate which packages we need...
    case "$Distro" in

        # Note: Do not place commas between packages! Bash treats them as part
        #       of the array element...

        # Arch: Gave up trying to determine dependencies...
        # [Aa]rch)
        #    # Note: Rolling release, so no code name...
        #    PackagesRequired=("gtk3" "libffi" "python-gobject")
        #    ;;

        # gNewSense: No support. deltah based off of Ubuntu 6.06, but does not 
        #  even have Python3 available...
        # gNewSense)
        #    ;;

        # Ubuntu or official...
        [Uu]buntu)

            # Which release?
            case "$DistroCodeName" in

                # Precise... (12.04)
                "precise")
                    PackagesRequired=(                  \
                        "python3-gi"                    \
                        "python3-cairo"                 \
                        "python3-gi-cairo")
                ;;

                # Quantal... (12.10)
                "quantal")
                    PackagesRequired=(                  \
                        "python3-gi"                    \
                        "python3-cairo"                 \
                        "python3-gi-cairo"              \
                        "gir1.2-gst-plugins-base-1.0"   \
                        "gir1.2-gtk-3.0"                \
                        "libgstreamer1.0-0"             \
                        "gstreamer1.0-plugins-base"     \
                        "gstreamer1.0-plugins-good")
                ;;

                # Raring... (13.04)
                "raring")
                    PackagesRequired=(                  \
                        "python3-gi"                    \
                        "python3-cairo"                 \
                        "python3-gi-cairo"              \
                        "gir1.2-gst-plugins-base-1.0"   \
                        "gir1.2-gtk-3.0"                \
                        "libgstreamer1.0-0"             \
                        "gstreamer1.0-plugins-base"     \
                        "gstreamer1.0-plugins-good")
                ;;

                # Unknown release...
                *)
                    # Try to guess in the hopes of forward compatibility...
                    PackagesRequired=(                  \
                        "python3-gi"                    \
                        "python3-cairo"                 \
                        "python3-gi-cairo"              \
                        "gir1.2-gst-plugins-base-1.0"   \
                        "gir1.2-gtk-3.0"                \
                        "libgstreamer1.0-0"             \
                        "gstreamer1.0-plugins-base"     \
                        "gstreamer1.0-plugins-good")
                    echo "Warning: Unknown Ubuntu release ($DistroCodeName)." \
                        "Guessing dependencies..."
                ;;

            esac
            ;;

        # CentOS: Not supported because Python3 unavailable...
        # CentOS)
        #    ;;

        # Fedora or derivative...
        [Ff]edora)

            # Which release?
            case "$DistroCodeName" in

                # Beefy Miracle... (18)
                "Beefy Miracle")
                    PackagesRequired=("python3-gobject")
                ;;

                # Schrödinger’s Cat... (19)
                "Schrödinger’s Cat")
                    PackagesRequired=(                  \
                        "python3"                       \
                        "python3-gobject"               \
                        "python3-cairo"                 \
                        "gstreamer1-plugins-good"       \
                        "gstreamer1-plugins-base"       \
                        "gobject-introspection"         \
                        "cairo-gobject"                 \
                        "gstreamer1")
                ;;

                # Unknown release...
                *)
                    # Try to guess...
                    PackagesRequired=(                  \
                        "python3"                       \
                        "python3-gobject"               \
                        "python3-cairo"                 \
                        "gstreamer1-plugins-good"       \
                        "gstreamer1-plugins-base"       \
                        "gobject-introspection"         \
                        "cairo-gobject"                 \
                        "gstreamer1")
                    echo "Warning: Unknown Fedora release ($DistroCodeName)." \
                        "Guessing dependencies..."
                ;;

            esac
            ;;

        # Debian...
        [Dd]ebian)

            # Which release?
            case "$DistroCodeName" in
                
                # Debian Wheezy. Squeeze doesn't have the needed dependencies...
                "wheezy")
                    PackagesRequired=(      \
                        "python3-gi"        \
                        "python3-cairo"     \
                        "python3-gi-cairo")
                ;;

                # Unknown release...
                *)
                    # Try to guess...
                    PackagesRequired=(      \
                        "python3-gi"        \
                        "python3-cairo"     \
                        "python3-gi-cairo")
                    echo "Warning: Unknown Debian release ($DistroCodeName)." \
                        "Guessing dependencies..."
                ;;

            esac
            ;;

        # Unknown distro...
        *)
            zenity --error \
                --title="Avaneya: Viking Lander Remastered" \
                --window-icon=$Icon \
                --text="I'm sorry, but your distribution $Distro $DistroCodeName is not supported."
            exit 1
            ;;
    esac

    # Number of packages that are always needed...
    local PackagesRequiredCount=${#PackagesRequired[*]}

    # Check that each required package is installed...
    for (( Index=0; Index<$PackagesRequiredCount; Index++)); do
        CheckPackageInstalled ${PackagesRequired[${Index}]}
    done
    KillZenity

    # Some packages still need to be installed...
    if [ ${#PackagesMissing[*]} -gt 0 ]; then

        # Print to console missing packages...
        echo "Packages which need to be installed... ${PackagesMissing[*]}"

        # Alert user...
        zenity \
            --info \
            --title="$Title" \
            --window-icon=$Icon \
            --text="Welcome! This application needs the following additional software you can install with your operating system's package manager. Once it is installed, just restart the application.\n\n\t${PackagesMissing[*]}" \
            --ok-label="Ok"

        # Eject the media only if we are running off of removable media...
        EjectRequested=true

        # Exit with error...
        exit 1

    # User has everything that they need...
    else
        echo "No packages needed to be installed..."
    fi
}

# Takes a package name as a single parameter and returns true if it is
#  installed. Also adds the name of the package if missing to PackagesMissing
#  global array...
CheckPackageInstalled()
{
    case "$DistroPackageManager" in

        # Apt based...
        apt)
            CheckDebInstalled $1
        ;;
        
        # Yum based...
        yum)
            CheckRPMInstalled $1
        ;;

        # Unknown...
        *)
            zenity --error \
                --title="Error" \
                --window-icon=$Icon \
                --text="I'm sorry, but your package manager is not supported..."
            exit 1
            ;;
    esac
}

# Takes a Debian package name as a single parameter and returns true if it is
#  installed. Also adds the name of the package if missing to PackagesMissing
#  global array...
CheckDebInstalled()
{
    # Get name of package to check as only argument...
    local Package=$1

    # Check if the package is installed...
    echo -n "Checking if $Package is installed... "
    TestInstalled=( `LANGUAGE="C" apt-cache policy $Package | grep "Installed:" ` )

    # Installed...
    if [[ (-n "${TestInstalled}") && ("${TestInstalled[1]}" != "(none)")]]
    then
        echo -e $SymbolStatusOk
        return 1

    # Found in the package database, but not installed, or not even found in 
    #  the package data, and therefore not installed...
    else
        echo -e $SymbolStatusFail
        PackagesMissing=("${PackagesMissing[*]}" $Package)
        return 0
    fi
}

# Takes a RPM package name as a single parameter and returns true if it is
#  installed. Also adds the name of the package if missing to PackagesMissing
#  global array...
CheckRPMInstalled()
{
    # Get name of package to check as only argument...
    local Package=$1

    # Check if the package is installed...
    echo -n "Checking if $Package is installed... "
    OldLanguage=$LANGUAGE
    LANGUAGE="C" yum list installed $Package &> /dev/null
    Status=$?
    LANGUAGE=$OldLanguage

    # Installed...
    if [ $Status == 0 ]
    then
        echo -e $SymbolStatusOk
        return 1

    # Not installed...
    else
        echo -e $SymbolStatusFail
        PackagesMissing=("${PackagesMissing[*]}" $Package)
        return 0
    fi
}

# Eject the media only if we are running off of removable media...
EjectRemovableMedia()
{
    # Find the mount point it is located on...
    MountPoint=`df "$AutostartScriptDirectory" | awk 'NR==2{print $NF}'`

    # Alert user of our intentions...
    echo -n "Checking if" $MountPoint "is removable media..."

    # Eject if it is removable media. That is, under /media/* according to sect
    #  3.11.1 of the FHS...
    if [[ $MountPoint == /media/* ]]; then

        # Attempt to eject the media...
        echo -e $SymbolStatusOk
        echo "Attempting eject..."
        exec eject $MountPoint 2> /dev/null

        # Old approach: eject the disc by first trying CDROM eject method, then
        #  by SCSI method...
        # eject -r -s 2> /dev/null

        ## Report whether it was successful or not...
        #if [ $? == 0 ]; then
        #    echo -e $SymbolStatusOk
        #else
        #    echo -e $SymbolStatusFail
        #fi

    # Not running off of removable media, so don't try to eject...
    else
        echo -e $SymbolStatusFail
    fi
}

# Entry point...
Main()
{
    # Print banner...
    PrintBanner

    # Make sure we are not being run as root...
    if [ "$(id -u)" == "0" ]; then
       echo "This script should not be run as root..." 1>&2
       exit 1
    fi

    # Lock the script to ensure no other instances are running...
    LockScript

    # Zenity has come on most GNU distros...
    echo -n "Checking for zenity... "
    if [ ! -x "`which zenity`" ]; then
	    echo $SymbolStatusFail
	    exit 1
	else
	    echo $SymbolStatusOk
        echo "Using zenity `zenity --version`... "
    fi

    # Give user visual feedback as soon as possible that something is 
    #  happening...
    zenity --progress \
            --title="$Title" \
            --window-icon=$Icon \
            --text="Please wait a moment while the software loads..." \
            --pulsate \
            --auto-close \
            --auto-kill &
    ZenityProcessID=$!

    # Display user's locale...
    echo "User's LANG is... ${LANG}"
    echo "User's LANGUAGE is... ${LANGUAGE}"

    # Identify the user's distro...
    IdentifyDistro

    # Prepare the runtime environment as specific to user's distro...
    InitializeRuntime

    # Find the launcher...
    FindLauncherMain
    
    # Set the VikingExtractor locale directory environment if running off of
    #  disc and not in standard FHS..
    SetVikingExtractorLocaleDirectory

    # Run the launcher...
    echo -n "Launching GUI using... "

        # First try with Python 3...
        if [ -x "`which python3`" ]; then
            echo "python3 $SymbolStatusOk"
            /usr/bin/env python3 "${PythonLauncherMain}" "${Arguments[@]}"
        
        # ...and if that still doesn't work, then we're out of luck...
        else
            echo $SymbolStatusFail
            zenity --error \
                --title="Error" \
                --window-icon=$Icon \
                --text="I'm sorry, but I couldn't find your Python 3 runtime."
            exit 1
        fi

    # Done...
    exit 0
}

# Setup traps...
trap OnExit EXIT SIGINT SIGQUIT SIGSTOP

# Begin execution in Main...
Main;

